### PR TITLE
Issue 2537 Setting context for the handleError call

### PR DESCRIPTION
**Pull request by cahirodoherty-learningpool**
Fixes https://github.com/adaptlearning/adapt_framework/issues/2537

### CODE REVIEW

**Comment by moloko** [comment]
> 
> 
> can we get rid of self?
> 
> ```
> if (responseType == 'choice') {
>     response = response.map(checkIdentifier.bind(this));
> } else {
>     response = response.map(function(r) {
>         var identifiers = r.split('.');
>         return checkIdentifier(identifiers[0]) + '.' + checkIdentifier(identifiers[1]);
>     }.bind(this));
> }
> ```

Would that work though? I'd have thought you'd have to do something more like this:
```js
response = response.map(function(r) {
  var identifiers = r.split('.');
  return checkIdentifier(identifiers[0]).bind(this) + '.' + checkIdentifier(identifiers[1]).bind(this);
});
```
which, if correct, is starting to look a little clumsy

**Comment by NayanKhedkar** [comment]
> Would that work though? I'd have thought you'd have to do something more like this:
> 
> ```js
> response = response.map(function(r) {
>   var identifiers = r.split('.');
>   return checkIdentifier(identifiers[0]).bind(this) + '.' + checkIdentifier(identifiers[1]).bind(this);
> });
> ```
> 
> which, if correct, is starting to look a little clumsy

yes @moloko you are right

```
response = response.map(function(r) {
  var identifiers = r.split('.');
  return checkIdentifier.call(this,identifiers[0]) + '.' + checkIdentifier.call(this,identifiers[1]);
}.bind(this));
```
yeah its look a little clumsy. Drop It

**Comment by moloko** [comment]
@cahirodoherty-learningpool before I merge can I just check that you tested this fixes the issue?

**Comment by cahirodoherty-learningpool** [comment]
> @cahirodoherty-learningpool before I merge can I just check that you tested this fixes the issue?

Hi @moloko I did indeed, and it now displays the error message as expected, instead of falling over

**Pull request merged**
