### PR TITLE
Added keyboard shortcut to invoke Spoor logger

### PR DESCRIPTION
**Pull request by chris-steele**
Hold keys 'd', 'e', 'v' together to invoke log window. The included jquery.keycombo extension could perhaps go to core libs?

### CODE REVIEW

**Comment by chris-steele** [comment]
Hmm - is that when running from a web server?

**Comment by moloko** [comment]
yes - running from LMS

**Comment by chris-steele** [comment]
OK that should be fixed now

**Comment by moloko** [comment]
yep, works great for me in FF now

since there's nothing else in Adapt Core that requires keyboard shortcuts, it's hard to argue for putting jquery.keycombo in core. But perhaps it should be moved to the extension's 'libraries' folder in line with [this](https://github.com/adaptlearning/adapt-contrib-trickle/pull/73)?

**Comment by moloko** [comment]
great stuff, now if you could just implement a 'tap d-e-v out in morse code' option for touch devices that would be great ;-)

**Comment by chris-steele** [comment]
Haha, nice idea. I wonder, perhaps, for simplicity we could watch for a gesture like:

1. single finger touch (held)
2. second finger taps three times

Simple to use, unlikely to be triggered accidentally. What do you think?

**Comment by moloko** [comment]
sorry @chris-steele you do need to change the framework version in README as well, just noticed that this has been done in other plugins (well, Slider)

**Pull request merged**
