### PR TITLE
Fix: Close loading screen via router.hideLoading() (fixes #291)

### LINKED ISSUE #291: Close loading screen via router.hideLoading()
### Subject of the issue
When closing the loading screen, use `router.hideLoading()` instead of hiding it directly with jQuery.

Relates to Core issue [423](https://github.com/adaptlearning/adapt-contrib-core/issues/423)

### PR DESCRIPTION
**Pull request by swashbuck**
Fix #291 

### Fix
* Close loading screen via router.hideLoading()

### CODE REVIEW

**Review by oliverfoster — APPROVED** [review]

**Comment by oliverfoster** [comment]
Could you bump the fw version in the package.json to correspond where appropriate.

**Comment by swashbuck** [comment]
> Could you bump the fw version in the package.json to correspond where appropriate.

@oliverfoster The required FW should only be **5.10.0**. The new Core changes in PR [#435](https://github.com/adaptlearning/adapt-contrib-core/pull/435) are not breaking. So, I think we’re fine?

**Comment by oliverfoster** [comment]
Fair enough. This is the first time the `hideLoading` and `showLoading` functions have been used outside of the core and the first time they've been updated in three years. Perhaps I got a little over-excited?

**Review by joe-allen-89 — APPROVED** [review]
👍

**Pull request merged**
