### PR TITLE
Fix: Amend default schema value for `_setCompletedWhenFailed`

### LINKED ISSUE #256: schema `_setCompletedWhenFailed` should default to true
### Subject of the issue/enhancement/features
To maintain previous behaviour, `_setCompletedWhenFailed` should default to true in [properties.schema](https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/properties.schema#L256).

### PR DESCRIPTION
**Pull request by danielghost**
Fixes #256.

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by joe-allen-89 — APPROVED** [review]

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/properties.schema#L256

**Comment by danielghost** [comment]
@oliverfoster - the [properties.schema](https://github.com/adaptlearning/adapt-contrib-spoor/blob/91f44ccc3d9384fbae6b7e7594c93f9d511d09db/properties.schema#L256) had already been updated in the commit.

**Comment by oliverfoster** [comment]
So it has. Apologies.

**Review by oliverfoster — APPROVED** [review]

**Pull request merged**
