### PR TITLE
Resolves #1329, adds support for dynamic props in imsmanifest.xml

### PR DESCRIPTION
**Pull request by brian-learningpool**
The 'title' and 'description' are now passed through to their placeholders in imsmanifest.xml.

### CODE REVIEW

**Comment by moloko** [comment]
It would be great to be able to replace all instances of `"adapt_"` in the manifest with some kind of unique id, strictly speaking some of these IDs are meant to be unique to the SCO on the LMS.

Is this possible and is there any suitable 'courseid' generated by the AT that could be used?

**Comment by brian-learningpool** [comment]
Hi @moloko, yes, the `_id` value as held in MongoDB is unique to the authoring tool instance which created it.

Would that do?

**Comment by moloko** [comment]
sounds ideal

**Comment by brian-learningpool** [comment]
@moloko, having just had a chance to get back to this there's a slight snag.  While we do have unique `_id` values from the authoring tool, the one for the course model is actually replaced with the string "course". 

Can we raise this as a separate issue if needs be?  A timestamp is another option.

**Comment by moloko** [comment]
Yes let's deal with that separately, getting this stuff in is far more important

**Pull request merged**
