### PR TITLE
updating ie conditionals to include adapt id

### PR DESCRIPTION
**Pull request by ciaranlp**
main.html was missing the id="adapt" onthe ie conditionals

### CODE REVIEW

**Comment by tomgreenfield** [comment]
Could this be added to [scorm_test_harness.html](https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/required/scorm_test_harness.html) as well please?

**Comment by ciaranlp** [comment]
done @tomgreenfield

**Comment by tomgreenfield** [comment]
+1

**Comment by brian-learningpool** [comment]
+1

**Comment by moloko** [comment]
+1

**Pull request merged**
