### PR TITLE
 Fixes #53 - js error if _spoor is not set in config.json

### LINKED ISSUE #53: Spoor generates an error that _isEnabled is not defined
Old courses will not have an isEnabled property.

Some defensive programming is required on this line:
https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/js/adapt-contrib-spoor.js#L25

### PR DESCRIPTION
**Pull request by dennis-learningpool**

### CODE REVIEW

**Comment by olivermartinfoster** [comment]
+1 cool

**Comment by olivermartinfoster** [comment]
(we should probably make sure all of the extensions fall-over nicely when they configurations are missing)

**Comment by brian-learningpool** [comment]
+1

**Comment by taylortom** [comment]
+1, and +1 for Ollie's suggestion

**Comment by moloko** [comment]
would it not also be necessary to check for the existence of _isEnabled as well?

I thought that not existing was the problem @brian-learningpool  was highlighting here: https://github.com/adaptlearning/adapt-contrib-spoor/issues/53

**Comment by dennis-learningpool** [comment]
Hi Matt,

The issue brian highlights is that if `this.data` is null, then attempting to access `this.data._isEnabled` will result in a Javascript error. As long as the existence of `this.data` is confirmed first, there will be no error in accessing the `_isEnabled` property, whether it is set or not.

**Comment by moloko** [comment]
OK I see now

+1 in that case

**Pull request merged**
