### PR TITLE
allow the authoring tool to suppress SCORM errors when previewing

### PR DESCRIPTION
**Pull request by moloko**
see [ABU-1130](https://adaptlearning.atlassian.net/browse/ABU-1130)

### CODE REVIEW

**Comment by oliverfoster** [comment]
+1 - i still think it'd be better to rename main.html to index.html and add spoor/required/index_lms.html with a link in the imsmanifest.html.

**Comment by oliverfoster** [comment]
+1

**Comment by tomgreenfield** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Pull request merged**
