### PR TITLE
refactoring to simplify and remove redundant code

### PR DESCRIPTION
**Pull request by develop-stuartohare**

### CODE REVIEW

**Comment by moloko** [comment]
+1 much tidier, thanks. tested on Moodle & SCORM Cloud in both SCORM 1.2 and SCORM 2004 using IE8, Chrome, Firefox & iOS9

**Comment by oliverfoster** [comment]
+1

**Comment by danielghost** [comment]
+1

**Comment by taylortom** [comment]
+1 looks good to me

**Pull request merged**
