### PR TITLE
Release/2.0.1 - Version Bump

### PR DESCRIPTION
**Pull request by oliverfoster**
* version bump for v2.0.1
* save and restore fixes
* bring inline with develop

### CODE REVIEW

**Comment by belal-almassri-spongeuk** [comment]
+1

**Comment by zenduo** [comment]
+1

**Comment by jovianshadow** [comment]
+1

**Comment by chucklorenz** [comment]
Does "_shouldStoreResponses" need to be added to the README? Re: https://github.com/adaptlearning/adapt_framework/blob/master/src/course/config.json#L21

**Comment by moloko** [comment]
@chucklorenz definitely, well spotted. @oliverfoster could you add something about this quickly?

**Pull request merged**
