### PR TITLE
updates to allow for better validation

### PR DESCRIPTION
**Pull request by moloko**
see https://github.com/adaptlearning/adapt_framework/issues/997

remove the 'encoding' meta tag as it is not valid
remove 'language' attribute from script tags, these are not needed
remove 'role' attribute from button tag, it is not needed

### CODE REVIEW

**Comment by oliverfoster** [comment]
+1 tabbing is off

**Comment by moloko** [comment]
should be fixed now

**Comment by hrajotia** [comment]
+1

**Comment by brian-learningpool** [comment]
+1

**Pull request merged**
