### PR TITLE
issue-1044: return learner_id

### PR DESCRIPTION
**Pull request by oliverfoster**
https://github.com/adaptlearning/adapt_framework/issues/1044

### CODE REVIEW

**Comment by tomgreenfield** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by moloko** [comment]
+1

Now the use of 'student' for the 'student_name' property looks really stupid though

**Comment by chris-steele** [comment]
+1

**Comment by moloko** [comment]
in retrospect would have been better to have a `student` object with properties `name` and `id`. to which we could have added `firstname` and `lastname`.

**Comment by moloko** [comment]
your `learner` object suggestion is a good one, please could we go with that instead?

**Comment by oliverfoster** [comment]
ok, i'm going to update with:
```
"learner": { "name", "firstname", "lastname", "id" }
```

**Comment by moloko** [comment]
I would prefer `getLearnerInfo` as a name, otherwise this looks great

**Comment by moloko** [comment]
@chris-steele @hrajotia @tomgreenfield could you review again, please?

**Comment by oliverfoster** [comment]
+1 Matt's bits :D

**Comment by chris-steele** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by tomgreenfield** [comment]
:+1:

**Pull request merged**
