### PR TITLE
add support for storing the user's choice of language

### PR DESCRIPTION
**Pull request by moloko**
in the appropriate SCORM data element (where supported) - see https://github.com/adaptlearning/adapt_framework/issues/1404

### CODE REVIEW

**Comment by moloko** [comment]
I have tested this on:
* Moodle
* Saba Content Lab
* SCORM Cloud (as both SCORM 1.2 and SCORM 2004 4th edition)

Unfortunately all of those have support for `cmi.student_preference.language` - so I'm unable to test that it fails gracefully when that data element isn't supported... it should work fine, I'd just prefer to know for sure!

If anyone has access to an LMS that they know doesn't support `cmi.student_preference.language` I can share a test SCO with you to try out...

**Comment by oliverfoster** [comment]
is there a sister pr for the languagePicker?

**Comment by moloko** [comment]
@oliverfoster no because it already does that - though now you mention it I can't for the life of me figure out **how** it is doing it; I assumed there was a call to `Adapt.offlineStorage.set("lang", newlang);` somewhere in languagePicker but apparently not....! time for some forensic debugging

**Comment by moloko** [comment]
aha: https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/app.js#L228

**Comment by oliverfoster** [comment]
if it's not supported on the LMS the language picker won't save it's language in suspend data any more?

**Comment by oliverfoster** [comment]
ignore me, i just read your comment

**Pull request merged**
