### PR TITLE
add a defer call to delay the call to setupEventListeners 

### PR DESCRIPTION
**Pull request by moloko**
just long enough for all the block completion data to be restored - fixes [#1149](https://github.com/adaptlearning/adapt_framework/issues/1149)

To replicate this issue, launch the out-of-the-box course on an LMS and complete a bunch of components. Then quit and relaunch with the debugger on and you'll see that each time a block has its completion data restored, this triggers a call to set suspend_data:
<details>
<summary>Moodle debug log showing the multiple calls to set suspend_data</summary>
```
Fri, 22 Jul 2016 12:37:56 GMT: LMSInitialize("", "") => 0
Fri, 22 Jul 2016 12:37:56 GMT: LMSGetValue("cmi.core.lesson_status") - incomplete => 0
Fri, 22 Jul 2016 12:37:56 GMT: Commit("", "") => 0
Fri, 22 Jul 2016 12:37:56 GMT: LMSCommit("AJAXResult", "true") => 0
Fri, 22 Jul 2016 12:37:56 GMT: LMSCommit("result", "true") => 0
Fri, 22 Jul 2016 12:37:56 GMT: LMSCommit("", "") => 0
Fri, 22 Jul 2016 12:37:57 GMT: LMSGetValue("cmi.suspend_data") - {"completion":"111111111111000000000","questions":"","_isCourseComplete":false,"_isAssessmentPassed":false,"a11y":false} => 0
Fri, 22 Jul 2016 12:37:57 GMT: LMSGetValue("cmi.suspend_data") - {"completion":"111111111111000000000","questions":"","_isCourseComplete":false,"_isAssessmentPassed":false,"a11y":false} => 0
Fri, 22 Jul 2016 12:37:57 GMT: LMSGetValue("cmi.core.lesson_location") - => 0
Fri, 22 Jul 2016 12:37:57 GMT: LMSGetValue("cmi.core.score.raw") - => 0
Fri, 22 Jul 2016 12:37:57 GMT: LMSGetValue("cmi.core.lesson_status") - incomplete => 0
Fri, 22 Jul 2016 12:37:57 GMT: LMSGetValue("cmi.core.student_name") - Leathes, Matt => 0
Fri, 22 Jul 2016 12:37:57 GMT: LMSSetValue("cmi.suspend_data", "{"completion":"100000000000000000000","questions":"","_isCourseComplete":false,"_isAssessmentPassed":false,"a11y":false}") => 0
Fri, 22 Jul 2016 12:37:57 GMT: LMSSetValue("cmi.suspend_data", "{"completion":"110000000000000000000","questions":"","_isCourseComplete":false,"_isAssessmentPassed":false,"a11y":false}") => 0
Fri, 22 Jul 2016 12:37:57 GMT: LMSSetValue("cmi.suspend_data", "{"completion":"111000000000000000000","questions":"","_isCourseComplete":false,"_isAssessmentPassed":false,"a11y":false}") => 0
Fri, 22 Jul 2016 12:37:57 GMT: LMSSetValue("cmi.suspend_data", "{"completion":"111100000000000000000","questions":"","_isCourseComplete":false,"_isAssessmentPassed":false,"a11y":false}") => 0
Fri, 22 Jul 2016 12:37:57 GMT: LMSSetValue("cmi.suspend_data", "{"completion":"111110000000000000000","questions":"","_isCourseComplete":false,"_isAssessmentPassed":false,"a11y":false}") => 0
Fri, 22 Jul 2016 12:37:57 GMT: LMSSetValue("cmi.suspend_data", "{"completion":"111111000000000000000","questions":"","_isCourseComplete":false,"_isAssessmentPassed":false,"a11y":false}") => 0
Fri, 22 Jul 2016 12:37:57 GMT: LMSSetValue("cmi.suspend_data", "{"completion":"111111100000000000000","questions":"","_isCourseComplete":false,"_isAssessmentPassed":false,"a11y":false}") => 0
Fri, 22 Jul 2016 12:37:57 GMT: LMSSetValue("cmi.suspend_data", "{"completion":"111111110000000000000","questions":"","_isCourseComplete":false,"_isAssessmentPassed":false,"a11y":false}") => 0
Fri, 22 Jul 2016 12:37:57 GMT: LMSSetValue("cmi.suspend_data", "{"completion":"111111111000000000000","questions":"","_isCourseComplete":false,"_isAssessmentPassed":false,"a11y":false}") => 0
Fri, 22 Jul 2016 12:37:57 GMT: LMSSetValue("cmi.suspend_data", "{"completion":"111111111100000000000","questions":"","_isCourseComplete":false,"_isAssessmentPassed":false,"a11y":false}") => 0
Fri, 22 Jul 2016 12:37:57 GMT: LMSSetValue("cmi.suspend_data", "{"completion":"111111111110000000000","questions":"","_isCourseComplete":false,"_isAssessmentPassed":false,"a11y":false}") => 0
Fri, 22 Jul 2016 12:37:57 GMT: LMSSetValue("cmi.suspend_data", "{"completion":"111111111111000000000","questions":"","_isCourseComplete":false,"_isAssessmentPassed":false,"a11y":false}") => 0
Fri, 22 Jul 2016 12:37:57 GMT: LMSGetValue("cmi.core.lesson_location") - => 0
Fri, 22 Jul 2016 12:37:58 GMT: LMSSetValue("cmi.core.lesson_location", "") => 0
Fri, 22 Jul 2016 12:38:08 GMT: LMSSetValue("cmi.core.session_time", "0000:00:11.36") => 0
Fri, 22 Jul 2016 12:38:08 GMT: LMSSetValue("cmi.core.exit", "") => 0
Fri, 22 Jul 2016 12:38:08 GMT: Commit("", "") => 0
```
</details>

This code change will fix it so that you should just get this:
<details>
<summary>Moodle debug log from the same course running the amended code</summary>
```
Fri, 22 Jul 2016 12:50:45 GMT: LMSInitialize("", "") => 0
Fri, 22 Jul 2016 12:50:45 GMT: LMSGetValue("cmi.core.lesson_status") - incomplete => 0
Fri, 22 Jul 2016 12:50:46 GMT: Commit("", "") => 0
Fri, 22 Jul 2016 12:50:46 GMT: LMSCommit("AJAXResult", "true") => 0
Fri, 22 Jul 2016 12:50:46 GMT: LMSCommit("result", "true") => 0
Fri, 22 Jul 2016 12:50:46 GMT: LMSCommit("", "") => 0
Fri, 22 Jul 2016 12:50:46 GMT: LMSGetValue("cmi.suspend_data") - {"completion":"111111111111000000000","questions":"","_isCourseComplete":false,"_isAssessmentPassed":false,"a11y":false} => 0
Fri, 22 Jul 2016 12:50:46 GMT: LMSGetValue("cmi.suspend_data") - {"completion":"111111111111000000000","questions":"","_isCourseComplete":false,"_isAssessmentPassed":false,"a11y":false} => 0
Fri, 22 Jul 2016 12:50:46 GMT: LMSGetValue("cmi.core.lesson_location") - => 0
Fri, 22 Jul 2016 12:50:46 GMT: LMSGetValue("cmi.core.score.raw") - => 0
Fri, 22 Jul 2016 12:50:46 GMT: LMSGetValue("cmi.core.lesson_status") - incomplete => 0
Fri, 22 Jul 2016 12:50:46 GMT: LMSGetValue("cmi.core.student_name") - Leathes, Matt => 0
Fri, 22 Jul 2016 12:50:47 GMT: LMSGetValue("cmi.core.lesson_location") - => 0
Fri, 22 Jul 2016 12:50:47 GMT: LMSSetValue("cmi.core.lesson_location", "") => 0
Fri, 22 Jul 2016 12:50:49 GMT: LMSSetValue("cmi.core.session_time", "0000:00:02.92") => 0
Fri, 22 Jul 2016 12:50:49 GMT: LMSSetValue("cmi.core.exit", "") => 0
Fri, 22 Jul 2016 12:50:49 GMT: Commit("", "") => 0
```
</summary>

### CODE REVIEW

**Comment by moloko** [comment]
FYI this PR looks a lot neater if you view it in Chrome ;-)

**Comment by brian-learningpool** [comment]
+1 -- nice job.

**Comment by oliverfoster** [comment]
+1

**Comment by tomgreenfield** [comment]
+1

**Pull request merged**
