### PR TITLE
Add more information to the spoor

### PR DESCRIPTION
**Pull request by belal-almassri-spongeuk**
This PR  will add component['_isCorrect']  and component['_score']  to the spoor.

### CODE REVIEW

**Comment by belal-almassri-spongeuk** [comment]
Thanks @oliverfoster  for your help.

**Comment by oliverfoster** [comment]
this keeps the score and correctness across sessions to allow other extensions to use them

**Comment by oliverfoster** [comment]
+1

**Comment by zenduo** [comment]
+1

**Comment by moloko** [comment]
+1

**Pull request merged**
