### PR TITLE
update from jquery-cookie to js-cookie

### PR DESCRIPTION
**Pull request by moloko**
* refactor offline_API_wrapper.js to remove some duplication
* add cookie settings into scorm_test_harness.html with comments

resolves https://github.com/adaptlearning/adapt_framework/issues/2798

### CODE REVIEW

**Comment by moloko** [comment]
I've tested this in IE11, Chrome and Firefox. Also checked it works if spoor configured to use SCORM 2004.

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by eleanor-heath — APPROVED** [review]

**Review by chris-steele — APPROVED** [review]
Working fine in Safari (macos 11.1)

**Review by oliverfoster — APPROVED** [review]
tested in chrome

**Pull request merged**
