### PR TITLE
adds ability to switch off SCORM tracking via _isEnabled setting in config.json; complete re-write of the README

### PR DESCRIPTION
**Pull request by moloko**
The develop branch was hideously out of date compare to master, so to do this I had to pull all the changes down from master - that's why there's a load of commit messages from last year.

### CODE REVIEW

**Comment by oliverfoster** [comment]
+1, that is a lovely commit path for such tiny changes x)

**Comment by brian-learningpool** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by moloko** [comment]
It took me ages to work out how to do it the right way, too!

**Pull request merged**
