### PR TITLE
ABU-940: Properly disable offlineStorage implementation

### PR DESCRIPTION
**Pull request by oliverfoster**
* when spoor_isEnabled: false, stop offlineStorage API calling SCORM functions

### CODE REVIEW

**Comment by moloko** [comment]
+1

**Comment by moloko** [comment]
that said, would this:
{{{
useTemporaryStore: function() {
	var cfg = Adapt.config.get('_spoor');

	if (!scorm.lmsConnected || !cfg || cfg._isEnabled === false) return true;
	return false;
}
}}}
Not be a slightly tidier way of doing it?

**Comment by oliverfoster** [comment]
Yea, nice spot, I'll change it in the morning.

**Comment by hrajotia** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by zenduo** [comment]
+1

**Pull request merged**
